// Generated by ReScript, PLEASE EDIT WITH CARE


var left = document.getElementById("left");

var right = document.getElementById("right");

var top = document.getElementById("right");

var bottom = document.getElementById("right");

console.log(left, right, top, bottom);

export {
  left ,
  right ,
  top ,
  bottom ,
}
/* left Not a pure module */
